In [2]:
#import libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

In [7]:
# Read dataset
vine = pd.read_csv('winequality-white.csv',';')

In [8]:
vine.head()

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  ...  density    pH  sulphates  alcohol  quality
0            7.0              0.27         0.36            20.7      0.045  ...   1.0010  3.00       0.45      8.8        6
1            6.3              0.30         0.34             1.6      0.049  ...   0.9940  3.30       0.49      9.5        6
2            8.1              0.28         0.40             6.9      0.050  ...   0.9951  3.26       0.44     10.1        6
3            7.2              0.23         0.32             8.5      0.058  ...   0.9956  3.19       0.40      9.9        6
4            7.2              0.23         0.32             8.5      0.058  ...   0.9956  3.19       0.40      9.9        6

[5 rows x 12 columns]

In [9]:
vine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 459.3 KB

In [12]:
vine.describe()

       fixed acidity  volatile acidity  citric acid  residual sugar  ...           pH    sulphates      alcohol      quality
count    4898.000000       4898.000000  4898.000000     4898.000000  ...  4898.000000  4898.000000  4898.000000  4898.000000
mean        6.854788          0.278241     0.334192        6.391415  ...     3.188267     0.489847    10.514267     5.877909
std         0.843868          0.100795     0.121020        5.072058  ...     0.151001     0.114126     1.230621     0.885639
min         3.800000          0.080000     0.000000        0.600000  ...     2.720000     0.220000     8.000000     3.000000
25%         6.300000          0.210000     0.270000        1.700000  ...     3.090000     0.410000     9.500000     5.000000
50%         6.800000          0.260000     0.320000        5.200000  ...     3.180000     0.470000    10.400000     6.000000
75%         7.300000          0.320000     0.390000        9.900000  ...     3.280000     0.550000    11.400000     6.000000
max        14.200000          1.100000     1.660000       65.800000  ...     3.820000     1.080000    14.200000     9.000000

[8 rows x 12 columns]

In [13]:
vine.shape

(4898, 12)

In [32]:
vine.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Taste                   0
dtype: int64

In [19]:
#adding new feature as taste
vine['Taste']  = 'good'

In [20]:
vine.head()

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  ...    pH  sulphates  alcohol  quality  Taste
0            7.0              0.27         0.36            20.7      0.045  ...  3.00       0.45      8.8        6   good
1            6.3              0.30         0.34             1.6      0.049  ...  3.30       0.49      9.5        6   good
2            8.1              0.28         0.40             6.9      0.050  ...  3.26       0.44     10.1        6   good
3            7.2              0.23         0.32             8.5      0.058  ...  3.19       0.40      9.9        6   good
4            7.2              0.23         0.32             8.5      0.058  ...  3.19       0.40      9.9        6   good

[5 rows x 13 columns]

In [21]:
#labeling/classifing wine quality data as good(quality>7), normal(5<quality<7) and bad(quality<5)
vine.loc[(vine.quality<5),'Taste'] = 'Bad'
vine.loc[(vine.quality>7),'Taste'] = 'Good'
vine.loc[(vine.quality>=5) & (vine.quality<=7),'Taste'] = 'Normal'

In [22]:
vine.head()

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  ...    pH  sulphates  alcohol  quality   Taste
0            7.0              0.27         0.36            20.7      0.045  ...  3.00       0.45      8.8        6  Normal
1            6.3              0.30         0.34             1.6      0.049  ...  3.30       0.49      9.5        6  Normal
2            8.1              0.28         0.40             6.9      0.050  ...  3.26       0.44     10.1        6  Normal
3            7.2              0.23         0.32             8.5      0.058  ...  3.19       0.40      9.9        6  Normal
4            7.2              0.23         0.32             8.5      0.058  ...  3.19       0.40      9.9        6  Normal

[5 rows x 13 columns]

In [23]:
vine.tail()

      fixed acidity  volatile acidity  citric acid  residual sugar  ...  sulphates  alcohol  quality   Taste
4893            6.2              0.21         0.29             1.6  ...       0.50     11.2        6  Normal
4894            6.6              0.32         0.36             8.0  ...       0.46      9.6        5  Normal
4895            6.5              0.24         0.19             1.2  ...       0.46      9.4        6  Normal
4896            5.5              0.29         0.30             1.1  ...       0.38     12.8        7  Normal
4897            6.0              0.21         0.38             0.8  ...       0.32     11.8        6  Normal

[5 rows x 13 columns]

In [24]:
vine[vine.quality>7]

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  ...    pH  sulphates  alcohol  quality  Taste
17              6.2             0.660         0.48             1.2      0.029  ...  3.33       0.39     12.8        8   Good
20              6.2             0.660         0.48             1.2      0.029  ...  3.33       0.39     12.8        8   Good
22              6.8             0.260         0.42             1.7      0.049  ...  3.47       0.48     10.5        8   Good
68              6.7             0.230         0.31             2.1      0.046  ...  3.33       0.64     10.7        8   Good
74              6.7             0.230         0.31             2.1      0.046  ...  3.33       0.64     10.7        8   Good
...             ...               ...          ...             ...        ...  ...   ...        ...      ...      ...    ...
4765            5.2             0.300         0.34             1.5      0.038  ...  3.56       0.48     13.0        8   Good
4766            6.4             0.320         0.25             5.0      0.055  ...  3.27       0.50     12.4        8   Good
4786            4.4             0.320         0.39             4.3      0.030  ...  3.46       0.36     12.8        8   Good
4787            3.9             0.225         0.40             4.2      0.030  ...  3.57       0.36     12.8        8   Good
4802            5.8             0.280         0.34             2.2      0.037  ...  3.36       0.33     12.8        8   Good

[180 rows x 13 columns]

In [25]:
#inititating random forest object
model = RandomForestClassifier()

In [26]:
X = vine.loc[:,:'alcohol']

In [27]:
X.head()

   fixed acidity  volatile acidity  citric acid  residual sugar  ...  density    pH  sulphates  alcohol
0            7.0              0.27         0.36            20.7  ...   1.0010  3.00       0.45      8.8
1            6.3              0.30         0.34             1.6  ...   0.9940  3.30       0.49      9.5
2            8.1              0.28         0.40             6.9  ...   0.9951  3.26       0.44     10.1
3            7.2              0.23         0.32             8.5  ...   0.9956  3.19       0.40      9.9
4            7.2              0.23         0.32             8.5  ...   0.9956  3.19       0.40      9.9

[5 rows x 11 columns]

In [28]:
y = vine.Taste

In [29]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [33]:
# fittting model
model.fit(X_train,y_train)

RandomForestClassifier()

In [34]:
# model evalution
y_predict = model.predict(X_test)

In [35]:
accuracy_score(y_test,y_predict)

0.9455782312925171

In [36]:
confusion_matrix(y_test,y_predict)

array([[  12,    0,   41],
       [   0,   19,   38],
       [   9,    0, 1498]], dtype=int64)